### PR TITLE
Extract serial number from SSDP

### LINKED ISSUE #51: MAC address or some sort of  unique ID?
Hi,

Home Assistant is adding support for unique id's to devices and I was wondering if there are any sort of unique ID's available via the API? If not, is there a way to get the MAC address via this library?

Thank you for your work on this library. I use it daily via Home Assistant.

Regards,
Michal

### PR DESCRIPTION
**Pull request by postlund**
It's been a while since anything happened in this repo, but I would like to add a serial number field in order to implement `unique_id` in Home Assistant. It will only work in case the device is found by discovery, which will be a mandatory to use this.

Simple example:

```
>>> import rxv
>>> rxv.find()[0].serial_number
'ADBB61D0'
```

Fixes #51.

### CODE REVIEW

**Comment by wuub** [comment]
Nice. Thank you

**Comment by mihalski** [comment]
@postlund Thank you for this. Is there a way to use source_ignore, source_names and zone_ignore in conjunction with discovery? Apologies if this is the wrong place to ask.

**Comment by postlund** [comment]
@mihalski I'm not sure I understand what you mean?

**Comment by mihalski** [comment]
> @mihalski I'm not sure I understand what you mean?

My current configuration is:
```
media_player:
  - platform: yamaha
    host: 192.168.1.220
    source_ignore:
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "HDMI5"
      - "AirPlay"
      - "Bluetooth"
      - "MusicCast Link"
      - "NET RADIO"
      - "PHONO"
      - "Pandora"
      - "SERVER"
      - "Spotify"
      - "TUNER"
      - "USB"
      - "V-AUX"
      - "iPod (USB)"
    source_names:
      HDMI1: "PlayStation"
      HDMI2: "SHIELD"
      HDMI3: "Windows"
      HDMI4: "macOS"
    zone_ignore:
      - "Zone_2"
```

I can see how platform and host can be auto-discovered, but what about the rest of the configuration?
Is there any method to pass those parameters to the Yamaha integration when using discovery?

Thanks in advance. 

Regards,
Michal

**Comment by postlund** [comment]
@mihalski It's not possible to discover *your* particular configuration as only you know how what that looks like. Adding support for config flow however, would make it possible to discover the device automatically and expose configuration (the things you mention) as options so you can just tick them in the UI. This is an enabler for that as config entries (which are the artifact of a config flow) requires a unique id.

**Pull request merged**
