### PR TITLE
Fix a typo: ReponseException -> ResponseException

### PR DESCRIPTION
**Pull request by Raynes**
This is, of course, a breaking change but... It hurts to type out `ReponseException` in my code so I thought I'd propose it anyways.

### CODE REVIEW

**Comment by wuub** [comment]
Maybe add an alias
`ReponseException = ResponseException`
in rxv/exceptions.py?

It should allow for backward compatible release.

**Comment by wuub** [comment]
Also:
 - please add yourself to the Contributors list in README.md :)
 - if you want I would love to have a link to rxvc in the README as well (Projects using this library, or something like that) :)

**Comment by wuub** [comment]
Thanks for such quick reaction :) 
Please remove  env/.Python and .cache/ that got into one of the commits by mistake and I'll happily merge this :+1:

**Comment by Raynes** [comment]
Yeah, I noticed this last night but was too blurry eyed with sleep deprivation to fix it. I'll do it posthaste.

**Comment by Raynes** [comment]
Fixed. Sorry about that. Note that I rebased and force pushed so if you previously pulled this branch you'll want to re-do that.

**Comment by wuub** [comment]
Thank you @Raynes so much for this contribution.

**Pull request merged**
