### PR TITLE
Feature/add scenes and surround programs

### PR DESCRIPTION
**Pull request by HerrHofrat**
I've added the following functionality:

- Get list of available surround programs 
- Get/Set surround program
- Get list of available scenes
- Get/Set scene

Tested on a RX-V775

### CODE REVIEW

**Comment by HerrHofrat** [comment]
@wuub Just wanted to ask if you already had a look at it?

**Comment by HerrHofrat** [comment]
Oh sorry about that - I didn't get a notification :D will have a look at it today!

**Comment by wuub** [comment]
@HerrHofrat I'll take a look later today.

**Comment by wuub** [comment]
@HerrHofrat how much have you tested this?

**Comment by HerrHofrat** [comment]
I only have an RX-V775 to test with, where it is working.. Which one do you have? 
I will write feature tests by tomorrow - and also add my desc.xml

**Comment by wuub** [comment]
@HerrHofrat I'll merge this and add my changes, you can then verify that it works on your side as well. There is some strange things going on if scene selection behaves OK on your side, but we will make it work :)

**Comment by wuub** [comment]
Example of strange behaviour: When I select `r.scene = 'TV'` then `r.scene` returns `AV4` for some reason. 
:)

**Comment by HerrHofrat** [comment]
Hm.. That looks really strange.. Surround Programs setter/getter are working for you?

**Comment by wuub** [comment]
@HerrHofrat see this branch for changes that made it work on my side
https://github.com/wuub/rxv/tree/scenes_and_surround

**Comment by HerrHofrat** [comment]
I've tested your branch today - you're right - my scene selection didn't work well - apologies for that, seems I've commited a wrong revision. Seems like the receiver just returns the input for the scene - I also get AV4 when I set the scene to TV. Besides from that, everything else is working fine! I now committed the xml files from the rx-v775 - in case you need it for testing!

**Pull request merged**
