### PR TITLE
Implement logic to search multiple pages for a value.

### PR DESCRIPTION
**Pull request by HerrHofrat**
Hello,

I have more than 8 bookmarks in my net radio settings. When I want to start one that is not on the first page, the library can't find it. With this PR I've implemented a logic that - if not all entries are displayed on one page, the cursor jumps to the next one - as long as max_lines are not reached.

Let me know what you think!

Thanks!

### CODE REVIEW

**Comment by wuub** [comment]
The implementation looks a bit complicated and seems to handle only a single additional page (?). 

Do you think this could be refactored into a more abstract solution for searching a value in multiple menu pages?

**Comment by HerrHofrat** [comment]
It should search so long until max_lines are reached.

I'll refactor it and update the PR in the next days

**Comment by HerrHofrat** [comment]
I've updated the PR with a more structural approach

**Comment by wuub** [comment]
Superb. Thank you. I'll take a look and test it ASAP :)

**Pull request closed without merging**
